# Generated by Django 5.1.2 on 2025-12-12 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_data', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'verbose_name': 'Doctor Profile', 'verbose_name_plural': 'Doctor Profiles'},
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_data.specialization', verbose_name='Specialization'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('PATIENT', 'PATIENT'), ('DOCTOR', 'DOCTOR'), ('ADMIN', 'ADMIN')], default='PATIENT', max_length=10),
        ),
    ]
