# Generated by Django 5.1.2 on 2026-06-16 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=150, verbose_name='Medicine Name (EN)')),
                ('name_ar', models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم الدواء (بالعربي)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicines_images/', verbose_name='Medicine Image')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
            },
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms_ar',
            field=models.TextField(blank=True, null=True, verbose_name='الأعراض (بالعربي)'),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms_en',
            field=models.TextField(blank=True, null=True, verbose_name='Symptoms (EN)'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptoms',
            field=models.TextField(blank=True, null=True, verbose_name='Symptoms (General)'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(help_text='Enter the case diagnosis here', verbose_name='Diagnosis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='users.appointment', verbose_name='Related Appointment')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200, verbose_name='اسم الدواء')),
                ('dosage', models.CharField(help_text='مثلاً: 3 مرات يومياً', max_length=100, verbose_name='الجرعة')),
                ('duration', models.CharField(help_text='مثلاً: لمدة أسبوع', max_length=100, verbose_name='المدة')),
                ('instructions', models.TextField(blank=True, help_text='اكتب التعليمات بأي لغة (عربي أو إنجليزي)', null=True, verbose_name='التعليمات (Notes)')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='users.prescription', verbose_name='الروشتة')),
            ],
            options={
                'verbose_name': 'Prescription Medicine',
                'verbose_name_plural': 'Prescription Medicines',
            },
        ),
    ]
