# Generated by Django 5.1.2 on 2026-02-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='symptoms_ar',
            field=models.TextField(blank=True, null=True, verbose_name='الأعراض (بالعربي)'),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms_en',
            field=models.TextField(blank=True, null=True, verbose_name='Symptoms (EN)'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptoms',
            field=models.TextField(blank=True, null=True, verbose_name='Symptoms (General)'),
        ),
    ]
