# Generated by Django 5.1.2 on 2026-02-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_disease_symptoms_ar_disease_symptoms_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True, verbose_name='Blood Group'),
        ),
    ]
