# Generated by Django 5.1.2 on 2026-02-04 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_patientprofile_blood_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(help_text='اكتب تشخيص الحالة هنا', verbose_name='التشخيص (Diagnosis)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='users.appointment', verbose_name='الموعد المرتبط')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200, verbose_name='اسم الدواء')),
                ('dosage', models.CharField(help_text='مثلاً: 3 مرات يومياً', max_length=100, verbose_name='الجرعة')),
                ('duration', models.CharField(help_text='مثلاً: لمدة أسبوع', max_length=100, verbose_name='المدة')),
                ('instruction_ar', models.TextField(blank=True, null=True, verbose_name='تعليمات بالعربي')),
                ('instruction_en', models.TextField(blank=True, null=True, verbose_name='Instructions (EN)')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='users.prescription', verbose_name='الروشتة')),
            ],
        ),
    ]
