# Generated by Django 5.1.2 on 2026-02-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_prescription_prescriptionmedicine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'verbose_name': 'الروشتة', 'verbose_name_plural': 'الروشتات'},
        ),
        migrations.AlterModelOptions(
            name='prescriptionmedicine',
            options={'verbose_name': 'دواء الروشتة', 'verbose_name_plural': 'أدوية الروشتات'},
        ),
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='instruction_ar',
        ),
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='instruction_en',
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='instructions',
            field=models.TextField(blank=True, help_text='اكتب التعليمات بأي لغة (عربي أو إنجليزي)', null=True, verbose_name='التعليمات (Notes)'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(help_text='اكتب تشخيص الحالة هنا بالعربية أو الإنجليزية', verbose_name='التشخيص (Diagnosis)'),
        ),
    ]
