# Generated by Django 5.1.2 on 2026-02-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_prescription_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'verbose_name': 'Prescription', 'verbose_name_plural': 'Prescriptions'},
        ),
        migrations.AlterModelOptions(
            name='prescriptionmedicine',
            options={'verbose_name': 'Prescription Medicine', 'verbose_name_plural': 'Prescription Medicines'},
        ),
    ]
