# Generated by Django 5.1.2 on 2026-02-04 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_prescription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='users.appointment', verbose_name='Related Appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(help_text='Enter the case diagnosis here', verbose_name='Diagnosis'),
        ),
    ]
