# Generated by Django 5.2.8 on 2025-12-04 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, unique=True, verbose_name='اسم التخصص (عربي)')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='الوصف (عربي)')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='رمز الأيقونة (مثل FontAwesome)')),
            ],
            options={
                'verbose_name': 'تخصص طبي',
                'verbose_name_plural': 'التخصصات الطبية',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(verbose_name='تاريخ ووقت الموعد')),
                ('status', models.CharField(choices=[('PENDING', 'في انتظار التأكيد'), ('CONFIRMED', 'مؤكد'), ('COMPLETED', 'مكتمل'), ('CANCELLED', 'ملغي')], default='PENDING', max_length=10, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctorprofile', verbose_name='الطبيب')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patientprofile', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'موعد',
                'verbose_name_plural': 'المواعيد',
                'ordering': ['appointment_date'],
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=150, unique=True, verbose_name='اسم المرض (عربي)')),
                ('symptoms', models.TextField(blank=True, null=True, verbose_name='الأعراض')),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_data.specialization', verbose_name='التخصص المرتبط')),
            ],
            options={
                'verbose_name': 'مرض',
                'verbose_name_plural': 'الأمراض',
            },
        ),
    ]
