# Generated by Django 5.2.8 on 2025-12-04 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_data', '0001_initial'),
        ('users', '0003_alter_doctorprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'verbose_name': 'Disease', 'verbose_name_plural': 'Diseases'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Medical Specialization', 'verbose_name_plural': 'Medical Specializations'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(verbose_name='Appointment Date and Time'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctorprofile', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patientprofile', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name_ar',
            field=models.CharField(max_length=150, unique=True, verbose_name='Disease Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_data.specialization', verbose_name='Related Specialization'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptoms',
            field=models.TextField(blank=True, null=True, verbose_name='Symptoms'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Arabic)'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon Class'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name_ar',
            field=models.CharField(max_length=100, unique=True, verbose_name='Specialization Name (Arabic)'),
        ),
    ]
